<?php

// $Id$


function islandora_image_sp_required_fedora_objects() {


  $module_path = drupal_get_path('module', 'islandora_image_sp');

  // Put the form in the database
  $result = db_result(db_query('Select name from {xml_forms} where name = "%s"', 'Islandora Image MODS Form'));
  if (!$result) {
    $filename = "$module_path/xml/mods_image.xml";
    $form_as_string = file_get_contents($filename);
    $object = new stdClass();
    $object->name = 'Islandora Image MODS Form';
    $object->form = $form_as_string;
    $result = drupal_write_record('xml_forms', $object);
  }

  // Associates the form with the content model
  $result = db_result(db_query('Select content_model from {islandora_content_model_forms} where  content_model = "%s" and form_name = "%s"', 'islandora:collectionCModel', 'Islandora Image MODS Form'));
  if (!$result) {
    $object = new stdClass();
    $object->content_model = 'islandora:collectionCModel';
    $object->form_name = 'Islandora Image MODS Form';
    $object->dsid = 'MODS';
    $object->title_field = "['titleInfo']['title']";
    $object->transform = 'mods_to_dc.xsl';
    $result = drupal_write_record('islandora_content_model_forms', $object);
  }

  return array(
    'islandora_image_sp' => array(
      'module' => 'islandora_image_sp',
      'title' => 'Islandora Basic image Solution Pack',
      'objects' => array(
        array(
          'pid' => 'islandora:sp_basic_image',
          'label' => 'Islandora basic image content model',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/xml/BASIC_IMAGE_SP_CMODEL.xml",
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),

        array(
          'pid' => 'islandora:sp_basic_image_collection',
          'label' => 'Islandora Basic Image Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:top',
          'datastreams' => array(
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
              'mimetype' => 'image/png',
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/IMAGE-COLLECTION POLICY.xml",
            ),
          ),
        ),
      ),
    ),
  );
}

